create type user_status as enum ('ACTIVE', 'INACTIVE', 'LOCKED', 'DELETED');
create type role_code as enum ('STUDENT', 'TEACHER', 'CONTENT_MANAGER', 'ADMIN');
create type publish_status as enum ('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'PUBLISHED', 'HIDDEN', 'REJECTED', 'ARCHIVED');
create type active_status as enum ('ACTIVE', 'INACTIVE', 'ARCHIVED');
create type marker_type as enum ('QR_CODE', 'IMAGE_TARGET', 'MARKER_BASED', 'TEXTBOOK_PAGE');
create type marker_status as enum ('ACTIVE', 'INACTIVE', 'LOW_QUALITY', 'DELETED');
create type ar_content_type as enum ('MODEL_3D', 'ANIMATION', 'VIDEO', 'AUDIO', 'MIXED');
create type model_format as enum ('GLB', 'GLTF', 'FBX', 'OBJ', 'USDZ');
create type media_type as enum ('IMAGE', 'AUDIO', 'VIDEO', 'TEXT', 'DOCUMENT');
create type quiz_question_type as enum ('SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'TRUE_FALSE', 'SHORT_ANSWER');
create type progress_status as enum ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED');
create type scan_result as enum ('SUCCESS', 'FAILED', 'UNKNOWN_MARKER', 'NO_PERMISSION', 'UNSUPPORTED_DEVICE', 'CONTENT_NOT_PUBLISHED', 'ACCESS_DENIED', 'MODEL_LOAD_FAILED');
create type feedback_type as enum ('SCAN_ERROR', 'MODEL_ERROR', 'CONTENT_ERROR', 'AUDIO_ERROR', 'VIDEO_ERROR', 'QUIZ_ERROR', 'OTHER');
create type feedback_status as enum ('NEW', 'PROCESSING', 'RESOLVED', 'REJECTED');
create type review_status as enum ('PENDING', 'APPROVED', 'REJECTED', 'NEED_CHANGES');
create type assignment_status as enum ('ACTIVE', 'CLOSED', 'CANCELLED');
create type assignment_student_status as enum ('NOT_STARTED', 'IN_PROGRESS', 'SUBMITTED', 'COMPLETED', 'LATE');
create type audit_action as enum ('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'PUBLISH', 'APPROVE', 'REJECT', 'LOCK', 'UNLOCK', 'SCAN', 'SUBMIT_QUIZ');

create table users (
  id bigint generated by default as identity primary key,
  full_name varchar(150) not null,
  email varchar(150) unique not null,
  password_hash varchar(255) not null,
  phone varchar(30),
  avatar_url varchar(500),
  status user_status not null default 'ACTIVE',
  last_login_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone,
  deleted_at timestamp with time zone
);

create table roles (
  id bigint generated by default as identity primary key,
  code role_code unique not null,
  name varchar(100) not null,
  description text
);

create table user_roles (
  user_id bigint not null references users(id),
  role_id bigint not null references roles(id),
  assigned_at timestamp with time zone not null default now(),
  assigned_by bigint references users(id),
  primary key (user_id, role_id)
);

create table user_devices (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id),
  device_name varchar(255),
  os_name varchar(100),
  os_version varchar(100),
  browser_name varchar(100),
  browser_version varchar(100),
  supports_ar boolean default false,
  supports_webxr boolean default false,
  supports_camera boolean default true,
  last_used_at timestamp with time zone,
  created_at timestamp with time zone not null default now()
);

create table schools (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  code varchar(50) unique,
  address varchar(500),
  phone varchar(30),
  email varchar(150),
  status active_status not null default 'ACTIVE',
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone
);

create table grades (
  id bigint generated by default as identity primary key,
  name varchar(50) not null,
  level_number int not null,
  description text
);

create table classes (
  id bigint generated by default as identity primary key,
  school_id bigint references schools(id),
  grade_id bigint not null references grades(id),
  name varchar(100) not null,
  school_year varchar(20) not null,
  status active_status not null default 'ACTIVE',
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone
);

create table class_students (
  class_id bigint not null references classes(id),
  student_id bigint not null references users(id),
  joined_at timestamp with time zone not null default now(),
  left_at timestamp with time zone,
  is_active boolean not null default true,
  primary key (class_id, student_id)
);

create table teacher_classes (
  teacher_id bigint not null references users(id),
  class_id bigint not null references classes(id),
  assigned_at timestamp with time zone not null default now(),
  is_main_teacher boolean not null default false,
  primary key (teacher_id, class_id)
);

create table subjects (
  id bigint generated by default as identity primary key,
  code varchar(50) unique not null,
  name varchar(150) not null,
  description text,
  status active_status not null default 'ACTIVE',
  created_by bigint references users(id),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone
);

create table textbooks (
  id bigint generated by default as identity primary key,
  subject_id bigint not null references subjects(id),
  grade_id bigint not null references grades(id),
  title varchar(255) not null,
  publisher varchar(255),
  book_series varchar(255),
  school_year varchar(20),
  cover_image_url varchar(500),
  description text,
  status publish_status not null default 'DRAFT',
  created_by bigint references users(id),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone,
  unique (subject_id, grade_id, title)
);

create table class_textbooks (
  class_id bigint not null references classes(id),
  textbook_id bigint not null references textbooks(id),
  assigned_by bigint references users(id),
  assigned_at timestamp with time zone not null default now(),
  primary key (class_id, textbook_id)
);

create table chapters (
  id bigint generated by default as identity primary key,
  textbook_id bigint not null references textbooks(id),
  title varchar(255) not null,
  order_no int not null,
  description text,
  status publish_status not null default 'DRAFT',
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone,
  unique (textbook_id, order_no)
);

create table lessons (
  id bigint generated by default as identity primary key,
  chapter_id bigint not null references chapters(id),
  title varchar(255) not null,
  order_no int not null,
  objectives text,
  summary text,
  estimated_minutes int,
  status publish_status not null default 'DRAFT',
  created_by bigint references users(id),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone,
  unique (chapter_id, order_no)
);

create table textbook_pages (
  id bigint generated by default as identity primary key,
  textbook_id bigint not null references textbooks(id),
  lesson_id bigint references lessons(id),
  page_number int not null,
  page_title varchar(255),
  page_image_url varchar(500),
  description text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone,
  unique (textbook_id, page_number)
);

create table ar_markers (
  id bigint generated by default as identity primary key,
  textbook_page_id bigint not null references textbook_pages(id),
  marker_code varchar(100) unique not null,
  marker_type marker_type not null,
  marker_name varchar(255) not null,
  image_url varchar(500),
  target_file_url varchar(500),
  qr_payload varchar(500),
  quality_score numeric(5,2),
  width_cm numeric(8,2),
  height_cm numeric(8,2),
  status marker_status not null default 'ACTIVE',
  created_by bigint references users(id),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone
);

create table three_d_models (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  description text,
  file_url varchar(500) not null,
  thumbnail_url varchar(500),
  format model_format not null,
  size_mb numeric(10,2),
  polygon_count int,
  texture_count int,
  default_scale numeric(10,4) default 1,
  default_rotation_x numeric(10,4) default 0,
  default_rotation_y numeric(10,4) default 0,
  default_rotation_z numeric(10,4) default 0,
  license varchar(255),
  source_name varchar(255),
  uploaded_by bigint references users(id),
  status publish_status not null default 'DRAFT',
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone
);

create table ar_contents (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references lessons(id),
  marker_id bigint not null references ar_markers(id),
  default_model_id bigint references three_d_models(id),
  title varchar(255) not null,
  description text,
  content_type ar_content_type not null default 'MODEL_3D',
  instruction_text text,
  learning_goal text,
  position_x numeric(10,4) default 0,
  position_y numeric(10,4) default 0,
  position_z numeric(10,4) default 0,
  rotation_x numeric(10,4) default 0,
  rotation_y numeric(10,4) default 0,
  rotation_z numeric(10,4) default 0,
  scale_x numeric(10,4) default 1,
  scale_y numeric(10,4) default 1,
  scale_z numeric(10,4) default 1,
  status publish_status not null default 'DRAFT',
  version_no int not null default 1,
  created_by bigint references users(id),
  approved_by bigint references users(id),
  published_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone
);

create index idx_ar_contents_lesson_marker on ar_contents(lesson_id, marker_id);

create table ar_content_models (
  ar_content_id bigint not null references ar_contents(id),
  model_id bigint not null references three_d_models(id),
  display_order int not null default 1,
  is_default boolean not null default false,
  label varchar(255),
  primary key (ar_content_id, model_id)
);

create table model_labels (
  id bigint generated by default as identity primary key,
  model_id bigint not null references three_d_models(id),
  label_name varchar(255) not null,
  description text,
  position_x numeric(10,4) not null default 0,
  position_y numeric(10,4) not null default 0,
  position_z numeric(10,4) not null default 0,
  display_order int not null default 1
);

create table animations (
  id bigint generated by default as identity primary key,
  ar_content_id bigint not null references ar_contents(id),
  name varchar(255) not null,
  description text,
  animation_url varchar(500),
  animation_clip_name varchar(255),
  duration_seconds int,
  order_no int not null default 1,
  auto_play boolean not null default false,
  created_at timestamp with time zone not null default now()
);

create table media_assets (
  id bigint generated by default as identity primary key,
  ar_content_id bigint not null references ar_contents(id),
  asset_type media_type not null,
  title varchar(255),
  url varchar(500),
  transcript text,
  language_code varchar(10) default 'vi',
  duration_seconds int,
  order_no int not null default 1,
  created_at timestamp with time zone not null default now()
);

create table content_versions (
  id bigint generated by default as identity primary key,
  ar_content_id bigint not null references ar_contents(id),
  version_no int not null,
  title varchar(255),
  description text,
  snapshot_json jsonb,
  change_log text,
  status publish_status not null,
  created_by bigint references users(id),
  created_at timestamp with time zone not null default now(),
  unique (ar_content_id, version_no)
);

create table content_review_requests (
  id bigint generated by default as identity primary key,
  ar_content_id bigint not null references ar_contents(id),
  requested_by bigint not null references users(id),
  reviewed_by bigint references users(id),
  status review_status not null default 'PENDING',
  request_note text,
  review_comment text,
  requested_at timestamp with time zone not null default now(),
  reviewed_at timestamp with time zone
);

create table quizzes (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references lessons(id),
  title varchar(255) not null,
  description text,
  time_limit_minutes int,
  max_attempts int default 1,
  passing_score numeric(5,2) default 0,
  status publish_status not null default 'DRAFT',
  created_by bigint references users(id),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone
);

create table quiz_questions (
  id bigint generated by default as identity primary key,
  quiz_id bigint not null references quizzes(id),
  question_text text not null,
  question_type quiz_question_type not null default 'SINGLE_CHOICE',
  score numeric(6,2) not null default 1,
  order_no int not null,
  explanation text,
  image_url varchar(500)
);

create table quiz_answers (
  id bigint generated by default as identity primary key,
  question_id bigint not null references quiz_questions(id),
  answer_text text not null,
  is_correct boolean not null default false,
  explanation text,
  order_no int not null
);

create table quiz_attempts (
  id bigint generated by default as identity primary key,
  quiz_id bigint not null references quizzes(id),
  student_id bigint not null references users(id),
  attempt_no int not null,
  score numeric(6,2),
  total_score numeric(6,2),
  started_at timestamp with time zone not null default now(),
  submitted_at timestamp with time zone,
  duration_seconds int,
  is_passed boolean,
  unique (quiz_id, student_id, attempt_no)
);

create table quiz_attempt_answers (
  id bigint generated by default as identity primary key,
  attempt_id bigint not null references quiz_attempts(id),
  question_id bigint not null references quiz_questions(id),
  answer_id bigint references quiz_answers(id),
  answer_text text,
  is_correct boolean,
  score_earned numeric(6,2) default 0,
  unique (attempt_id, question_id, answer_id)
);

create table learning_progress (
  id bigint generated by default as identity primary key,
  student_id bigint not null references users(id),
  lesson_id bigint not null references lessons(id),
  status progress_status not null default 'NOT_STARTED',
  progress_percent numeric(5,2) not null default 0,
  total_scan_count int not null default 0,
  total_view_seconds int not null default 0,
  last_accessed_at timestamp with time zone,
  completed_at timestamp with time zone,
  unique (student_id, lesson_id)
);

create table scan_history (
  id bigint generated by default as identity primary key,
  student_id bigint references users(id),
  device_id bigint references user_devices(id),
  marker_id bigint references ar_markers(id),
  ar_content_id bigint references ar_contents(id),
  lesson_id bigint references lessons(id),
  result scan_result not null,
  detected_code varchar(150),
  error_message text,
  scanned_at timestamp with time zone not null default now()
);

create table ar_interactions (
  id bigint generated by default as identity primary key,
  student_id bigint not null references users(id),
  ar_content_id bigint not null references ar_contents(id),
  interaction_type varchar(100) not null,
  interaction_value varchar(255),
  duration_seconds int,
  created_at timestamp with time zone not null default now()
);

create table favorite_lessons (
  student_id bigint not null references users(id),
  lesson_id bigint not null references lessons(id),
  created_at timestamp with time zone not null default now(),
  primary key (student_id, lesson_id)
);

create table teacher_assignments (
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references users(id),
  class_id bigint not null references classes(id),
  lesson_id bigint not null references lessons(id),
  title varchar(255) not null,
  note text,
  due_date timestamp with time zone,
  status assignment_status not null default 'ACTIVE',
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone
);

create table assignment_students (
  assignment_id bigint not null references teacher_assignments(id),
  student_id bigint not null references users(id),
  status assignment_student_status not null default 'NOT_STARTED',
  submitted_at timestamp with time zone,
  score numeric(6,2),
  teacher_feedback text,
  primary key (assignment_id, student_id)
);

create table teacher_comments (
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references users(id),
  student_id bigint not null references users(id),
  lesson_id bigint references lessons(id),
  assignment_id bigint references teacher_assignments(id),
  comment_text text not null,
  created_at timestamp with time zone not null default now()
);

create table feedbacks (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id),
  ar_content_id bigint references ar_contents(id),
  marker_id bigint references ar_markers(id),
  lesson_id bigint references lessons(id),
  type feedback_type not null,
  rating int,
  message text not null,
  screenshot_url varchar(500),
  status feedback_status not null default 'NEW',
  handled_by bigint references users(id),
  handled_note text,
  created_at timestamp with time zone not null default now(),
  handled_at timestamp with time zone
);

create table system_settings (
  id bigint generated by default as identity primary key,
  setting_key varchar(150) unique not null,
  setting_value text,
  description text,
  updated_by bigint references users(id),
  updated_at timestamp with time zone
);

create table audit_logs (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id),
  action audit_action not null,
  entity_type varchar(100),
  entity_id bigint,
  old_value jsonb,
  new_value jsonb,
  ip_address varchar(100),
  user_agent varchar(500),
  created_at timestamp with time zone not null default now()
);

create index idx_ar_markers_code on ar_markers(marker_code);
create index idx_scan_history_student on scan_history(student_id, scanned_at desc);
create index idx_learning_progress_class_lookup on learning_progress(student_id, lesson_id);
create index idx_feedback_status on feedbacks(status, created_at desc);
