-- V2__add_payments_table.sql
-- Add is_premium column to users table
ALTER TABLE users ADD COLUMN is_premium BOOLEAN NOT NULL DEFAULT FALSE;

-- Create payments table to store transaction info
CREATE TABLE payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  txn_ref VARCHAR(100) NOT NULL UNIQUE,
  amount BIGINT NOT NULL,
  description VARCHAR(255),
  status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
  vnp_txn_no VARCHAR(100),
  vnp_response_code VARCHAR(50),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE
);
